name: Build

on: [push]

env:
  VERSION: ${{ github.run_number }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: publish
        run: make publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}